[package]
name = "solana-events-parser"
version = "0.1.0"
publish = true
edition = "2021"

[features]
default = ["solana", "anchor"]
unknown_log = []
solana = ["solana-client", "solana-sdk", "solana-transaction-status"]
anchor = ["solana", "anchor-lang", "base64"]

[dependencies]
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.5.4"
thiserror = "1.0.30"
simple_logger = "2.1.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
anyhow = "1.0.32"
async-trait = "0.1.53"
tokio = "1.14.1"

solana-client = { version = "1.10.12", optional = true }
solana-sdk = { version = "1.10.12", optional = true }
solana-transaction-status = { version = "1.10.12", optional = true }
anchor-lang = { git = "https://github.com/debridge-finance/anchor.git", branch = "accounts-from-pubkey", optional = true}
base64 = { version = "0.13.0", optional = true }
