[package]
name = "log-checker"
version = "0.0.0"
edition = "2021"

[dependencies]
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.5.6"
thiserror = "1.0.31"
diff-struct = { version = "0.4.1", git = "ssh://git@github.com/cyphersnake/diff-struct.git", branch = "master" }
